CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ProductName] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(400) NOT NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
	[RetailPrice] MONEY NOT NULL,
    [LastModified] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)
