CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ProductName] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(400) NOT NULL,
	[RetailPrice] MONEY NOT NULL,
	[ProductCost] MONEY NOT NULL,
	[QuantityInStock] INT NOT NULL,
	[ReservedQuantity] INT NOT NULL DEFAULT 0,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [LastModified] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[TaxId] INT NOT NULL,
    CONSTRAINT [FK_Product_Tax] FOREIGN KEY ([TaxId]) REFERENCES [Tax]([Id])
)
